CARS_INSTANCE_NAME=defaultInst

IS_FRESH_INSTALL=true

USER_INSTALL_DIR=/opt/opentext/cars/defaultInst

LDAP_HOST=opa.mydomain.com
LDAP_PORT=6366
LDAP_SUFFIX=o=mydomain.com
IS_NETWORK_INSTALLATION=1

LDAP_USER=cn=Directory Manager,o=mydomain.com
LDAP_PASSWORD=admin
INSTALLMODE=SSL_MODE

LDAP_CONFIG_PASSWORD=admin